#!/bin/bash

#------------------------------------------------#
# CREADOR   :  HACKING PCH                       #
# TELEGRAM  :  hackingpch2                       #
# FACEBOOK  :  @hackingpch                       #
# YOU-TUBE  :  HACKING PCH                       #
# SCRIPT    :  Seguridad                         #
#------------------------------------------------#
#            NINGUN SISTEMA ES SEGURO            #
z="
";CEz='}';bz='━╮\e';EBz='4m▕╱';HEz='fi';MDz='>> /';XBz='2m ]';UBz='m [$';QBz='NG P';lCz='ara ';iDz='sar ';cBz='bl="';aBz='ab="';VCz='  + ';uBz='----';BEz='es."';oCz='ree ';SDz='es/u';TDz='sr/e';Ez='m"';cz='[32m';fCz='36mE';Vz='▔▔╲\';rCz='vo$r';aDz=' {';bCz='$r" ';JCz='   +';ZCz='324 ';LCz='  SI';eDz='as g';jCz='egun';rDz='u te';oBz='/acc';HDz='ME/a';Tz='34m╱';fBz=' -x ';kBz='ermu';Nz='r■$a';TBz='   \';vCz='p';ADz='sh';Oz='█$r■';oDz=' PCH';Qz='32m┈';WBz='bl.0';Uz='▔▔▔▔';xBz='  EL';GCz='$r  ';xDz='guro';CBz='4m━╯';az='━━━━';sCz='php ';IDz=' "ba';SCz='CATE';UCz='  +-';hDz='or u';NCz='NES ';lDz='t de';xCz='d +x';RDz='/fil';DBz='┈┈╰╯';YDz='salu';jz='mTER';LBz='ador';vz='╰╯╭╮';iBz='ta/c';hz='━╮┈▏';wDz='s se';pDz='"aho';OCz='PROB';SBz='    ';LDz='sh" ';GEz='15';pCz='el a';ECz='UNA ';DDz='o.sh';NBz='37m:';Xz='m┈\e';mDz=' HAC';XCz='1982';WCz=' +52';Rz='┈┈┈┈';kCz='do p';lz='PASS';PBz='ACKI';Pz='$a█"';Cz='r="\';HCz='+"';tDz='al e';OBz='$r H';Hz='echo';XDz='rc';TCz=' AL ';yBz=' SCR';mCz='que ';kz='MUX-';hBz='a/da';sDz='rmin';PCz='LEMA';EEz=' pv ';jDz='mi S';VDz='ash.';BBz='┈┈┈▏';RCz='MUNI';WDz='bash';Gz='e[34';qz='┈┈┈"';FEz='-qL ';Lz='"$r■';wz='╰╯┈▏';fz='4m▕┈';gBz='/dat';KDz='HOME';mBz='les/';qCz='rchi';jBz='om.t';dDz='Much';sz='╮┃┈▏';qDz='ra t';Jz='"\e[';AEz=' ant';ODz='a/co';tz='4m╰┳';qBz='sh ]';iz='4m┃\';ICz='"$r ';ACz='IPT ';Yz='[34m';nCz='yo c';sBz='en';wBz='$bl ';KCz=' $bl';GBz='╲╱╲▏';eCz='+\e[';rBz='; th';eBz='if [';RBz='CH  ';Fz='a="\';HBz='"$r[';FBz='╲╱╲╱';ZDz='do()';Sz='┈\e[';xz='2m┈\';EDz=' $HO';dz='┈"';MBz=' \e[';bBz='6m"';Zz='╭━━━';Bz='r';gz='╭━╮╭';UDz='tc/b';oz='34m┃';DEz='do |';gDz='as p';fDz='raci';MCz=' TIE';GDz='nano';kDz='crip';cDz='[37m';YCz='1240';ZBz='v="\';yDz=' que';vBz='---+';BCz='SOLO';Mz='$a█$';IBz='$a>$';KBz='mCre';cCz='+---';nDz='KING';yCz=' acc';uCz='e.ph';FDz='ME';Wz='e[32';aCz='else';JBz='r] \';iCz='os s';PDz='m.te';JDz='sh $';BDz='mv a';rz='┃╭╯╰';ez='\e[3';uz='━━━╯';DCz='USA ';nBz='home';gCz='sper';lBz='x/fi';Kz='1m"';bDz='1m\e';CDz='cces';Dz='e[31';wCz='chmo';QCz='S CO';hCz='e un';NDz='data';FCz='VEZ ';dBz='7m"';pz='2m┈┈';CCz=' SE ';YBz='"';ABz='┈┈┃┃';pBz='eso.';yz='m┃\e';VBz='r 1$';tBz='"$r+';mz='WORD';dCz='" $r';Iz=' -e ';tCz='.tim';QDz='rmux';nz='.\e[';vDz='a ma';uDz='star';Az='clea';
eval "$Az$Bz$z$Cz$Dz$Ez$z$Fz$Gz$Ez$z$Hz$Iz$Jz$Kz$z$Hz$Iz$Lz$Mz$Nz$Oz$Mz$Nz$Oz$Mz$Nz$Oz$Mz$Nz$Oz$Mz$Nz$Oz$Mz$Nz$Oz$Mz$Nz$Oz$Mz$Nz$Oz$Mz$Nz$Oz$Mz$Nz$Oz$Mz$Nz$Oz$Mz$Nz$Oz$Pz$z$Hz$Iz$Jz$Qz$Rz$Rz$Rz$Rz$Sz$Tz$Uz$Vz$Wz$Xz$Yz$Zz$az$az$az$bz$cz$Rz$dz$z$Hz$Iz$Jz$Qz$Rz$Rz$Rz$Rz$ez$fz$gz$hz$ez$iz$Dz$jz$kz$lz$mz$nz$oz$ez$pz$qz$z$Hz$Iz$Jz$Qz$Rz$Rz$Rz$Rz$ez$fz$rz$sz$ez$tz$az$az$az$uz$ez$pz$qz$z$Hz$Iz$Jz$Qz$Rz$Rz$Rz$Rz$ez$fz$vz$wz$ez$xz$Gz$yz$cz$Rz$Rz$Rz$Rz$Rz$dz$z$Hz$Iz$Jz$Qz$Rz$Rz$Rz$Rz$ez$fz$ABz$BBz$ez$CBz$ez$pz$Rz$Rz$Rz$Rz$qz$z$Hz$Iz$Jz$Qz$Rz$Rz$Rz$Rz$ez$fz$DBz$BBz$ez$pz$Rz$Rz$Rz$Rz$Rz$dz$z$Hz$Iz$Jz$Qz$Rz$Rz$Rz$Rz$ez$EBz$FBz$GBz$ez$pz$Rz$Rz$Rz$Rz$Rz$dz$z$Hz$Iz$Lz$Mz$Nz$Oz$Mz$Nz$Oz$Mz$Nz$Oz$Mz$Nz$Oz$Mz$Nz$Oz$Mz$Nz$Oz$Mz$Nz$Oz$Mz$Nz$Oz$Mz$Nz$Oz$Mz$Nz$Oz$Mz$Nz$Oz$Mz$Nz$Oz$Pz$z$Hz$Iz$HBz$IBz$JBz$Wz$KBz$LBz$MBz$NBz$OBz$PBz$QBz$RBz$SBz$SBz$SBz$TBz$Wz$UBz$VBz$WBz$ez$XBz$YBz$z$Hz$z$ZBz$Wz$Ez$z$aBz$ez$bBz$z$cBz$ez$dBz$z$eBz$fBz$gBz$hBz$iBz$jBz$kBz$lBz$mBz$nBz$oBz$pBz$qBz$rBz$sBz$z$Hz$Iz$tBz$uBz$uBz$uBz$uBz$uBz$uBz$uBz$uBz$vBz$YBz$z$Hz$Iz$tBz$wBz$xBz$yBz$ACz$BCz$CCz$DCz$ECz$FCz$GCz$HCz$z$Hz$Iz$tBz$uBz$uBz$uBz$uBz$uBz$uBz$uBz$uBz$vBz$YBz$z$Hz$Iz$ICz$SBz$JCz$uBz$uBz$uBz$uBz$uBz$uBz$uBz$uBz$uBz$vBz$YBz$z$Hz$Iz$ICz$SBz$JCz$KCz$LCz$MCz$NCz$OCz$PCz$QCz$RCz$SCz$TCz$GCz$HCz$z$Hz$Iz$ICz$SBz$JCz$uBz$uBz$uBz$uBz$uBz$uBz$uBz$uBz$uBz$vBz$YBz$z$Hz$Iz$ICz$SBz$SBz$SBz$SBz$SBz$SBz$UCz$uBz$uBz$uBz$uBz$vBz$YBz$z$Hz$Iz$ICz$SBz$SBz$SBz$SBz$SBz$SBz$VCz$wBz$WCz$XCz$YCz$ZCz$GCz$HCz$z$Hz$Iz$ICz$SBz$SBz$SBz$SBz$SBz$SBz$UCz$uBz$uBz$uBz$uBz$vBz$YBz$z$aCz$z$Hz$Iz$bCz$cCz$uBz$uBz$uBz$uBz$uBz$uBz$uBz$uBz$uBz$uBz$uBz$HCz$z$Hz$Iz$dCz$eCz$fCz$gCz$hCz$iCz$jCz$kCz$lCz$mCz$nCz$oCz$pCz$qCz$rCz$HCz$z$Hz$Iz$bCz$cCz$uBz$uBz$uBz$uBz$uBz$uBz$uBz$uBz$uBz$uBz$uBz$HCz$z$sCz$tCz$uCz$vCz$z$wCz$xCz$yCz$pBz$ADz$z$BDz$CDz$DDz$EDz$FDz$z$GDz$EDz$HDz$CDz$DDz$z$Hz$IDz$JDz$KDz$oBz$pBz$LDz$MDz$NDz$gBz$ODz$PDz$QDz$RDz$SDz$TDz$UDz$VDz$WDz$XDz$z$YDz$ZDz$aDz$z$Hz$Iz$Jz$bDz$cDz$dDz$eDz$fDz$gDz$hDz$iDz$jDz$kDz$lDz$mDz$nDz$oDz$YBz$z$Hz$Iz$pDz$qDz$rDz$sDz$tDz$uDz$vDz$wDz$xDz$yDz$AEz$BEz$z$Hz$z$CEz$z$YDz$DEz$EEz$FEz$GEz$z$HEz"

